# Generated by Django 3.2.12 on 2022-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный номер')),
                ('unique_hash', models.CharField(max_length=20, unique=True, verbose_name='Уникальный хэш')),
                ('tx_hash', models.CharField(max_length=20, verbose_name='Хэш транзакции создания токена')),
                ('media_url', models.TextField(max_length=20, verbose_name='URL с произвольным изображением')),
                ('owner', models.TextField(verbose_name='Адрес пользователя в сети Ethereum')),
            ],
        ),
    ]
