# Generated by Django 3.2.12 on 2022-03-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный номер'),
        ),
    ]
