# Generated by Django 3.2.12 on 2022-03-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='unique_hash',
            field=models.CharField(max_length=21, verbose_name='Уникальный хэш'),
        ),
    ]
