# Generated by Django 3.2.12 on 2022-03-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_token_unique_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='tx_hash',
        ),
        migrations.AlterField(
            model_name='token',
            name='media_url',
            field=models.TextField(max_length=20, null=True, verbose_name='URL с произвольным изображением'),
        ),
    ]
