# Generated by Django 3.2.12 on 2022-03-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_token_unique_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='unique_hash',
            field=models.CharField(max_length=20, unique=True, verbose_name='Уникальный хэш'),
        ),
    ]
