# Generated by Django 3.2.12 on 2022-03-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_token_unique_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='owner',
            field=models.TextField(unique=True, verbose_name='Адрес пользователя в сети Ethereum'),
        ),
    ]
