# Generated by Django 3.2.12 on 2022-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_token_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='media_url',
            field=models.TextField(max_length=20, verbose_name='URL с произвольным изображением'),
        ),
        migrations.AlterField(
            model_name='token',
            name='tx_hash',
            field=models.TextField(unique=True, verbose_name='Хэш транзакции создания токена'),
        ),
    ]
