# Generated by Django 3.2.12 on 2022-03-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220331_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='mediaURL',
            new_name='media_url',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='uniqueHash',
            new_name='unique_hash',
        ),
    ]
